# Generated by Django 3.2.3 on 2021-07-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_no', models.IntegerField()),
                ('stud_name', models.CharField(max_length=200)),
                ('stud_dob', models.DateField()),
                ('stud_doj', models.DateField()),
            ],
        ),
    ]
